// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf2VQxH53uioZpzrDhADZ6009rvQ23KEA',
    appId: '1:991731982146:web:08002d57f8c42838b9b2db',
    messagingSenderId: '991731982146',
    projectId: 'workout-pro-5bc78',
    authDomain: 'workout-pro-5bc78.firebaseapp.com',
    storageBucket: 'workout-pro-5bc78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXZ8_gMHlSk0ysD9gbaZ1wZf2VN1Ux9oE',
    appId: '1:991731982146:android:91f175f1d6c7a037b9b2db',
    messagingSenderId: '991731982146',
    projectId: 'workout-pro-5bc78',
    storageBucket: 'workout-pro-5bc78.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf2VQxH53uioZpzrDhADZ6009rvQ23KEA',
    appId: '1:991731982146:web:cfa12ebf128a44dcb9b2db',
    messagingSenderId: '991731982146',
    projectId: 'workout-pro-5bc78',
    authDomain: 'workout-pro-5bc78.firebaseapp.com',
    storageBucket: 'workout-pro-5bc78.firebasestorage.app',
  );
}
